#pragma once

//set SSL_HELPERS_PLATFORM_### macro

#if defined(TEST_PLATFORM_ANDROID) || defined(ANDROID) // SSL_HELPERS_PLATFORM_ANDROID
#if !defined(SSL_HELPERS_PLATFORM_ANDROID)
#define SSL_HELPERS_PLATFORM_ANDROID
#endif
#if !defined(SSL_HELPERS_PLATFORM_MOBILE)
#define SSL_HELPERS_PLATFORM_MOBILE
#endif
#elif defined(TEST_PLATFORM_IOS) || defined(PLATFORM_IOS) // SSL_HELPERS_PLATFORM_IOS
#if !defined(SSL_HELPERS_PLATFORM_IOS)
#define SSL_HELPERS_PLATFORM_IOS
#endif
#if !defined(SSL_HELPERS_PLATFORM_MOBILE)
#define SSL_HELPERS_PLATFORM_MOBILE
#endif
#elif defined(TEST_PLATFORM_WINDOWS) || defined(_WINDOWS) || defined(_WIN32) // SSL_HELPERS_PLATFORM_WINDOWS
#if !defined(SSL_HELPERS_PLATFORM_WINDOWS)
#define SSL_HELPERS_PLATFORM_WINDOWS
#endif
#endif
